spring:
  datasource:
    url: jdbc:mysql://localhost:3306/geha_sajang?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    initialization-mode: always
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: root
    data: classpath:schema.sql, classpath:data.sql
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: true
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

logging:
  level:
    org.hibernate.SQL: debug
    org.hibernate.type: trace #쿼리 파라미터에 어떤 타입의 어떤 데이터가 들어가는지 로그에 찍힘
    org.springframework.security: DEBUG

cloud:
  aws:
    s3:
      bucket: lynn-s3-test
    region:
      static: ap-northeast-2
    stack:
      auto: false
    credentials:
      instanceProfile: true
